### ISSUE TITLE
Beginning

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Discord-Bot#19]
titles

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#requests`.

**Comment by CSab6482** [comment]
![17B64312-0790-4BFA-AA4E-049B2E50EF1F](https://user-images.githubusercontent.com/53708281/108250396-352f8480-7124-11eb-9aa0-cc24bc2a510b.jpeg)

**Comment by CSab6482** [comment]
It look like this is a problem with the bot as a whole, not just with the word request

**Comment by cynical89** [comment]
This is an issue with quotation marks

” vs "
