### ISSUE TITLE
Okay

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Discord-Bot#20]
this

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#requests`.

**Comment by CSab6482** [comment]
![3E2124CC-3988-4EF8-9662-D4CE9F0FD714](https://user-images.githubusercontent.com/53708281/108251899-01555e80-7126-11eb-819f-e06c3919900b.jpeg)

**Comment by cynical89** [comment]
Didn't mean to close this ticket

**Comment by cynical89** [comment]
![image](https://user-images.githubusercontent.com/14186276/108254202-90a34780-710f-11eb-970a-b079dc085474.png)

**Comment by cynical89** [comment]
this is an issue with quotation marks 

” vs "
